tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "inverse-surface": "#203243",
        "on-primary": "#ffffff",
        "tertiary-fixed": "#ffe08b",
        "on-background": "#091d2e",
        "on-tertiary-fixed": "#241a00",
        "on-primary-fixed": "#131f00",
        "surface-container-low": "#edf4ff",
        "primary-container": "#5d7f13",
        "tertiary-container": "#d0a600",
        "on-secondary-container": "#663100",
        "primary-fixed-dim": "#add461",
        "surface-dim": "#c9dcf3",
        "error": "#ba1a1a",
        "surface-container-lowest": "#ffffff",
        "inverse-on-surface": "#e8f2ff",
        "on-tertiary": "#ffffff",
        "secondary-container": "#fc8f34",
        "secondary-fixed": "#ffdcc5",
        "on-tertiary-container": "#4f3d00",
        "secondary": "#944a00",
        "on-secondary": "#ffffff",
        "surface-container-high": "#d9eaff",
        "on-surface": "#091d2e",
        "on-error-container": "#93000a",
        "tertiary": "#745b00",
        "outline": "#747967",
        "background": "#f7f9ff",
        "on-surface-variant": "#444939",
        "surface-tint": "#496800",
        "on-error": "#ffffff",
        "surface-container": "#e3efff",
        "on-tertiary-fixed-variant": "#584400",
        "primary-fixed": "#c8f17a",
        "on-secondary-fixed": "#301400",
        "outline-variant": "#c4c9b4",
        "surface-variant": "#d1e4fb",
        "primary": "#476500",
        "surface-container-highest": "#d1e4fb",
        "on-secondary-fixed-variant": "#713700",
        "tertiary-fixed-dim": "#f1c100",
        "surface-bright": "#f7f9ff",
        "secondary-fixed-dim": "#ffb783",
        "on-primary-fixed-variant": "#364e00",
        "inverse-primary": "#add461",
        "surface": "#f7f9ff",
        "on-primary-container": "#faffe7",
        "error-container": "#ffdad6",
      },
      fontFamily: {
        headline: ["Comfortaa"],
        body: ["Comfortaa"],
        label: ["Comfortaa"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
    },
  },
};
